name: Build develop

on:
  push:
    branches: [develop]

concurrency: 
  group: build-develop-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  define_shared_variables:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.15.1

    steps:
      - name: Export variables to JSON
        id: varsStep
        uses: actions/github-script@v6
        with:
          script: core.setOutput('value', ${{ toJson(env) }})
    
    outputs:
      vars: ${{ steps.varsStep.outputs.value }}
  
  share_variables:
    uses: ./.github/workflows/define-shared-variables.yml
    needs: define_shared_variables
    with:
      shared-variables: ${{ needs.define_shared_variables.outputs.vars }}

  install_dependencies:
    uses: ./.github/workflows/install-dependencies.yml
    needs: share_variables

  build_lib:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: dynamic-form
      branch: temp
  
  build_showcase:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: showcase
      branch: temp
      artifactName: showcase

  deploy_to_firebase:
    uses: ./.github/workflows/deploy-to-firebase.yml
    needs: [build_showcase]
    with:
      branch: temp
      artifactName: showcase
      target: showcase
      channelId: live
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}