name: Build develop

on:
  push:
    branches: [deploy_showcase_to_firebases]

concurrency: 
  group: build-develop-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_lib:
    uses: ./.github/workflows/base-build.yml
    with:
      appName: dynamic-form
      branch: temp
  
  build_showcase:
    uses: ./.github/workflows/base-build.yml
    with:
      appName: showcase
      branch: temp
      artifactName: showcase

  deploy_to_firebase:
    uses: ./.github/workflows/deploy-to-firebase.yml
    needs: [build_showcase]
    with:
      branch: temp
      artifactName: showcase
      target: previews
      expires: 2d
      channelId: live
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  
  check_for_failures:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Finish build
    needs: [build_lib,create_showcase_preview_link]
    steps:
      - name: Check build status
        if: ${{ needs.build_lib.result != 'success' || needs.create_showcase_preview_link.result != 'success' }}
        run: exit 1