name: Build PR

on:
  pull_request:
    branches: [develop, master, 'feature/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4        

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build dynamic-form

      - name: Lint
        run: npm run lint dynamic-form

      - name: Test
        run: npm run test dynamic-form -- -c=single-run
