name: Build PR

on:
  pull_request:
    branches: [develop]

concurrency: 
  group: pr-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  define_shared_variables:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.15.1

    steps:
      - name: Export variables to JSON
        id: varsStep
        uses: actions/github-script@v6
        with:
          script: core.setOutput('value', ${{ toJson(env) }})
    
    outputs:
      vars: ${{ steps.varsStep.outputs.value }}
  
  shared_variables:
    uses: ./.github/workflows/define-shared-variables.yml
    needs: define_shared_variables
    with:
      shared-variables: ${{ needs.define_shared_variables.outputs.vars }}

  install_dependencies:
    uses: ./.github/workflows/install-dependencies.yml
    needs: shared_variables

  build_lib:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: dynamic-form
      branch: temp
  
  build_showcase:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: showcase
      branch: temp
      artifactName: showcase

  create_showcase_preview_link:
    uses: ./.github/workflows/deploy-to-firebase.yml
    needs: [build_showcase]
    with:
      branch: temp
      artifactName: showcase
      target: showcase
      expires: 2d
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  
  check_for_failures:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Finish build
    needs: [build_lib,create_showcase_preview_link]
    steps:
      - name: Check build status
        if: ${{ needs.build_lib.result != 'success' || needs.create_showcase_preview_link.result != 'success' }}
        run: exit 1