name: Build PR

on:
  pull_request:
    branches: [develop]

env:
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  CURRENT_BRANCH: ${{ github.head_ref }}
  BASE_BRANCH: ${{ github.base_ref }}
  NX_HEAD: origin/${{ github.head_ref }}
  NX_BASE: origin/${{ github.base_ref }}
  NX_BRANCH: ${{ github.head_ref }}
  SOMEVARKA: 'SAMOVAR'

concurrency: 
  group: pr-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  define_shared_variables:
    uses: ./.github/workflows/define-shared-variables.yml
    env:
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      CURRENT_BRANCH: ${{ github.head_ref }}
      BASE_BRANCH: ${{ github.base_ref }}
      NX_HEAD: origin/${{ github.head_ref }}
      NX_BASE: origin/${{ github.base_ref }}
      NX_BRANCH: ${{ github.head_ref }}
      SOMEVARKA: 'SAMOVAR'
    with:
      shared-variables: ${{ toJson(env) }}

  install_dependencies:
    uses: ./.github/workflows/install-dependencies.yml
    needs: define_shared_variables

  build_lib:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: dynamic-form
      branch: temp
  
  build_showcase:
    uses: ./.github/workflows/base-build.yml
    needs: install_dependencies
    with:
      appName: showcase
      branch: temp
      artifactName: showcase

  create_showcase_preview_link:
    uses: ./.github/workflows/deploy-to-firebase.yml
    needs: [build_showcase]
    with:
      branch: temp
      artifactName: showcase
      target: showcase
      expires: 2d
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  
  check_for_failures:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Finish build
    needs: [build_lib,create_showcase_preview_link]
    steps:
      - name: Check build status
        if: ${{ needs.build_lib.result != 'success' || needs.create_showcase_preview_link.result != 'success' }}
        run: exit 1